DATA wen;
set 'H:\wen';
RUN;

PROC contents data=wen;
run;

PROC print data=wen (obs=10);
run;

data wen;
set wen;
inc_new = HH_INCOME/10000;
run;

data wen;
set wen;
log_TOT_SALES= log(TOT_SALES+1);
run;

/*FORWARD SELECTION*/
PROC REG DATA = wen;
MODEL log_TOT_SALES =AVG_PRICE
BAKERY_PCT
BAKR_QTY
BEVRG_QTY
CHICKN_PCT
CHICK_QTY
DMA
DYPT_PCT_AF
DYPT_PCT_BR
DYPT_PCT_DINNER
DYPT_PCT_EVEN
DYPT_PCT_LU
DYPT_PCT_NITE
FRSTY_PCT
FRST_QTY
FRY_QTY
HAMBRGR_PCT
HAMBR_QTY
KID_PCT
KID_QTY
MEALDEAL_QTY
MealDeal_PCT
NUM_EARN_REDEEM
NUM_TXNS
OTHER_PCT
REDEEM_WELCOME
SALAD_PCT
SALD_QTY
SIZE_HH
TENURE
TOT_Rewards_EARN
TOT_UNITS
VALU_QTY
_DM
_EM
_SMS
_avg_TB_TRANS
inc_new
/ SELECTION = Forward slentry = 0.05 ;
run;

/*BACKWARD SELECTION*/
PROC REG DATA = wen;
MODEL log_TOT_SALES =AVG_PRICE
BAKERY_PCT
BAKR_QTY
BEVRG_QTY
CHICKN_PCT
CHICK_QTY
DMA
DYPT_PCT_AF
DYPT_PCT_BR
DYPT_PCT_DINNER
DYPT_PCT_EVEN
DYPT_PCT_LU
DYPT_PCT_NITE
FRSTY_PCT
FRST_QTY
FRY_QTY
HAMBRGR_PCT
HAMBR_QTY
KID_PCT
KID_QTY
MEALDEAL_QTY
MealDeal_PCT
NUM_EARN_REDEEM
NUM_TXNS
OTHER_PCT
REDEEM_WELCOME
SALAD_PCT
SALD_QTY
SIZE_HH
TENURE
TOT_Rewards_EARN
TOT_UNITS
VALU_QTY
_DM
_EM
_SMS
_avg_TB_TRANS
inc_new  / SELECTION = Backword slstay = 0.05;
run;

/*Stepwise Selection*/
PROC REG DATA = wen;
MODEL log_TOT_SALES =AVG_PRICE
BAKERY_PCT
BAKR_QTY
BEVRG_QTY
CHICKN_PCT
CHICK_QTY
DMA
DYPT_PCT_AF
DYPT_PCT_BR
DYPT_PCT_DINNER
DYPT_PCT_EVEN
DYPT_PCT_LU
DYPT_PCT_NITE
FRSTY_PCT
FRST_QTY
FRY_QTY
HAMBRGR_PCT
HAMBR_QTY
KID_PCT
KID_QTY
MEALDEAL_QTY
MealDeal_PCT
NUM_EARN_REDEEM
NUM_TXNS
OTHER_PCT
REDEEM_WELCOME
SALAD_PCT
SALD_QTY
SIZE_HH
TENURE
TOT_Rewards_EARN
TOT_UNITS
VALU_QTY
_DM
_EM
_SMS
_avg_TB_TRANS
inc_new  / SELECTION = stepwise slentry = 0.05 slstay = 0.05;
run;

/* BEST MODEL ACCORDING TO ALL THE ABOVE SELECTION METHODS*/
proc reg data=wen;
model log_TOT_SALES = TOT_UNITS AVG_PRICE HAMBRGR_PCT _avg_TB_TRANS HAMBR_QTY _EM SALAD_PCT OTHER_PCT MealDeal_PCT NUM_TXNS _DM DYPT_PCT_LU REDEEM_WELCOME SALD_QTY BAKERY_PCT BEVRG_QTY NUM_EARN_REDEEM TOT_Rewards_EARN DYPT_PCT_AF _SMS inc_new DMA FRY_QTY FRSTY_PCT ;
run;

/* Checking for Multicollinearity */
/* Examination of the Correlation Matrix */
proc corr data=wen;
var TOT_UNITS AVG_PRICE HAMBRGR_PCT _avg_TB_TRANS HAMBR_QTY _EM SALAD_PCT OTHER_PCT MealDeal_PCT NUM_TXNS _DM DYPT_PCT_LU REDEEM_WELCOME SALD_QTY BAKERY_PCT BEVRG_QTY NUM_EARN_REDEEM TOT_Rewards_EARN DYPT_PCT_AF _SMS inc_new DMA FRY_QTY FRSTY_PCT;
run;

/* Multicollinearity Investigation of VIF and Tolerance */
proc Reg data=wen;
Model log_TOT_SALES=TOT_UNITS AVG_PRICE HAMBRGR_PCT _avg_TB_TRANS HAMBR_QTY _EM SALAD_PCT OTHER_PCT MealDeal_PCT NUM_TXNS _DM DYPT_PCT_LU REDEEM_WELCOME SALD_QTY BAKERY_PCT BEVRG_QTY NUM_EARN_REDEEM TOT_Rewards_EARN DYPT_PCT_AF _SMS inc_new DMA FRY_QTY FRSTY_PCT/VIF TOL COLLIN;
run;
quit;

/* BEST MODEL ACCORDING TO ALL THE ABOVE SELECTION METHODS after dropping correlated columns*/
proc reg data=wen;
model log_TOT_SALES = TOT_UNITS AVG_PRICE HAMBRGR_PCT SALAD_PCT OTHER_PCT MealDeal_PCT BAKERY_PCT FRSTY_PCT  _avg_TB_TRANS HAMBR_QTY SALD_QTY BEVRG_QTY FRY_QTY DYPT_PCT_LU DYPT_PCT_AF REDEEM_WELCOME  TOT_Rewards_EARN  _SMS _EM _DM inc_new DMA  ;
run;

/* HETEROSKEDASTICITY */
proc reg data=wen;
model log_TOT_SALES = TOT_UNITS AVG_PRICE HAMBRGR_PCT SALAD_PCT OTHER_PCT MealDeal_PCT BAKERY_PCT FRSTY_PCT  _avg_TB_TRANS HAMBR_QTY SALD_QTY BEVRG_QTY FRY_QTY DYPT_PCT_LU DYPT_PCT_AF REDEEM_WELCOME  TOT_Rewards_EARN  _SMS _EM _DM inc_new DMA/SPEC ;
run;

proc model data= wen;
parms b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b20 b21 b22;
log_TOT_SALES= b0*TOT_UNITS + b1*AVG_PRICE + b3*HAMBRGR_PCT + b4*SALAD_PCT + b5*OTHER_PCT + b6*MealDeal_PCT + b7*BAKERY_PCT +b8*FRSTY_PCT  + b9*_avg_TB_TRANS + b10*HAMBR_QTY + b11*SALD_QTY + b12*BEVRG_QTY + b13*FRY_QTY + b14*DYPT_PCT_LU + b15*DYPT_PCT_AF + b16*REDEEM_WELCOME  + b17*TOT_Rewards_EARN  + b18*_SMS + b19*_EM + b20*_DM + b21*inc_new + b22*DMA;
fit log_TOT_SALES / white breusch=(1 TOT_UNITS AVG_PRICE HAMBRGR_PCT SALAD_PCT OTHER_PCT MealDeal_PCT BAKERY_PCT FRSTY_PCT  _avg_TB_TRANS HAMBR_QTY SALD_QTY BEVRG_QTY FRY_QTY DYPT_PCT_LU DYPT_PCT_AF REDEEM_WELCOME  TOT_Rewards_EARN  _SMS _EM _DM inc_new DMA );
run;

proc freq data=wen;
table NUM_TXNS;
run;
proc genmod data=wen;
model NUM_TXNS=TENURE AVG_PRICE NUM_EARN_REDEEM HH_INCOME SIZE_HH/dist=poisson link=log;
run;
proc genmod data=wen;
model NUM_TXNS=TENURE AVG_PRICE NUM_EARN_REDEEM HH_INCOME SIZE_HH/dist=negbin link=log;
run;
